version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies"
      - npm ci
  build:
    commands:
      - echo "Zipping deployment package"
      - zip -r function.zip index.mjs node_modules package.json package-lock.json
  post_build:
    commands:
      - echo "Updating Lambda code"
      - aws lambda update-function-code \
          --function-name avacompli-upload-api \
          --zip-file fileb://function.zip \
          --region us-east-1

artifacts:
  files:
    - function.zip
